# from repo root:
# docker-compose -f .docker/docker_manifest.yaml -p lodging up --build

networks:
  locally:

services:
  rest:
    build:
      context: ../aspnet
      dockerfile: ../.docker/machine.dockerfile
    depends_on:
      - data
    environment:
      ConnectionStrings__pgsql: 'Host=data;Database=LodgingData;Username=postgres;Password=LodgingData@2020;'
      ConnectionStrings__zipkin: 'http://trace:9411/'
    networks:
      - locally
    ports:
      - 8000:80

  data:
    environment:
      POSTGRES_PASSWORD: LodgingData@2020
    image: postgres:12
    networks:
      - locally

  trace:
    image: openzipkin/zipkin-slim
    networks:
      - locally
    ports:
      - 9411:9411

version: '3.8'
