networks:
  lodgingly:

services:
  rest:
    image: ghcr.io/rvtr/rvtrx-api-lodging:main-aspnet-rest
    depends_on:
      - data
    environment:
      ConnectionStrings__pgsql: 'Host=data;Database=LodgingData;Username=postgres;Password=LodgingData@2020;'
      ConnectionStrings__zipkin: 'http://trace:9411/'
    networks:
      - lodgingly
    ports:
      - 8002:80

  data:
    environment:
      POSTGRES_PASSWORD: LodgingData@2020
    image: postgres:13-alpine
    networks:
      - lodgingly

version: '3.8'
